CREATE  TABLE `aircpit`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  `employer_id` INT NOT NULL,
  `email` VARCHAR(255) NULL ,
  `mobile` VARCHAR(255) NULL ,
  `telephone` VARCHAR(255) NULL ,
  `country` INT(11) NULL ,
  `state` INT(11) NULL ,
  `district` INT(11) NULL ,
  `city` VARCHAR(255) NULL ,
  `experience` VARCHAR(255) NULL ,
  `industry` VARCHAR(255) NULL ,
  `functional_area` VARCHAR(255) NULL ,
  `address1` VARCHAR(255) NULL ,
  `address2` VARCHAR(255) NULL ,
  `file1` VARCHAR(255) NULL ,
  `createdBy` INT(11) NOT NULL ,
  `createdDate` DATETIME NOT NULL ,
  `modifiedBy` INT(11) NOT NULL ,
  `modifiedDate` DATETIME NOT NULL ,
  `status` ENUM('A','I','D') NOT NULL DEFAULT 'A' ,
  PRIMARY KEY (`id`));